- alias: Toggle bed light
  action:
  - alias: ''
    data:
      entity_id: switch.wall_switch_left_158d00014a5529
    service: switch.toggle
  condition: []
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_left_158d000183f051
    event_type: click
    platform: event

- alias: Toggle room light
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_right_158d000183f051
    event_type: click
    platform: event
  condition: []
  action:
  - service: light.toggle
    data:
      entity_id: light.philips_ceiling_room
    

- alias: Switch philips room scene
  condition: []
  trigger:
  - event_data:
      entity_id: binary_sensor.wall_switch_both_158d000183f051
    event_type: click
    platform: event
  action:
    entity_id: light.philips_ceiling_room
    data_template:
      scene: >-
        {% if states.light.philips_ceiling_room.attributes.scene == 4 %}
        1
        {% else %}
        {{ states.light.philips_ceiling_room.attributes.scene + 1 }}
        {% endif %}
    service: light.xiaomi_miio_set_scene

- alias: Turn lights on when someone arrived
  trigger:
  - platform: state
    entity_id: 
      - device_tracker.anton_phone
      - device_tracker.julsa_phone
    from: not_home
    to: home
  condition:
  - condition: numeric_state
    entity_id: sensor.illumination_7811dcb203d8
    below: 500
  action:
  - service: light.turn_on
    data:
      entity_id:
        - light.philips_ceiling_room
        - light.yeelight_white_f0b4290f2bf4
  #- service: switch.turn_on
  #  data:
  #    entity_id: switch.wall_switch_left_158d00014a5529

- alias: Turn off light when no one home
  trigger:
  - platform: state
    entity_id: 
      - device_tracker.anton_phone
      - device_tracker.julsa_phone
    from: home
    to: not_home
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.anton_phone
      state: not_home
    - condition: state
      entity_id: device_tracker.julsa_phone
      state: not_home

  action:
  - service: script.turn_off_lights
