homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.0516872
  longitude: 30.3370442
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Customization file
  customize: !include customize.yaml
  customize_glob:
    "group.all_*":
      hidden: false
  auth_providers:
  - type: homeassistant
  - type: legacy_api_password
    api_password: !secret http_password

recorder:
  db_url: !secret database_url
  purge_keep_days: 30
  purge_interval: 1


logger:
  default: info
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: critical

lovelace:
  mode: yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

media_player:
- platform: androidtv
  name: Mi TV
  host: 192.168.31.1
  adbkey: "adbkey"

prometheus:
  filter:
    include_domains:
      - sensor

# Enables configuration UI
config:

http:
  base_url: https://home.kaliwe.ru
  trusted_networks: [ 192.168.30.0/24 ]

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone:
- name: OpenWay
  latitude: 59.962516
  longitude: 30.334392
  icon: mdi:laptop

# Track the sun
sun:

# Text to speech
tts:
  - platform: yandextts
    api_key: !secret yandex_tts_token
    language: ru-RU
    voice: oksana

sensor: !include sensors.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
scene: !include scenes.yaml

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: gpasabtddj74uhop

discovery:
  ignore:
    - yeelight

light: !include devices/lights/light.yaml
yeelight: !include devices/lights/yeelight.yaml


vacuum:
  - platform: xiaomi_miio
    host: 192.168.30.4
    token: !secret vacuum_token

owntracks:

device_tracker:
  - platform: snmp
    host: 192.168.88.1
    community: public
    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
# - platform: mikrotik
#    host: 192.168.88.1
#    interval_seconds: 3
#    username: admin
#    method: wireless
#    password: !secret mikrotik_password
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false

person: !include person.yaml

google_assistant:
  project_id: home-assistant-integrati-5f446
  api_key: !secret google_api_key
  exposed_domains:
    - light
    - scene
  entity_config:
    switch.wall_switch_left_158d000302ef25:
      expose: true
      name: Toilet
    switch.wall_switch_right_158d000302ef25:
      expose: true
      name: Bathroom

switch: !include devices/switches/switch.yaml

mqtt:
  broker: 127.0.0.1
  username: hass
  password: !secret mqtt

notify:
  - platform: nfandroidtv
    name: Xiaomi TV
    host: 192.168.30.7

  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_home_channel

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - !secret telegram_bot_home_channel

fan:
  - platform: xiaomi_miio
    host: 192.168.30.9
    token: !secret humidifier_token

system_health:
stream:
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: local_file
    name: room_camera_disabled
    file_path: room_camera_disabled.png
  - platform: ffmpeg
    name: room_camera_ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.30.7/ch0_1.h264
  - platform: ffmpeg
    name: kitchen_camera_ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.30.8/ch0_0.h264

xiaomi_cooker:
  name: Xiaomi Rice Cooker
  host: 192.168.30.14
  token: 5a90f7e0432515a40d1d995094cc375b
