homeassistant:
  name: Home
  latitude: 60.0516872
  longitude: 30.3370442
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml
  customize_glob:
    "group.all_*":
      hidden: false
  auth_providers:
  - type: homeassistant
  - type: legacy_api_password
    api_password: !secret http_password




history:
  include:
    domains:
    - switch
    - person
    - light

logbook:
  include:
    domains:
    - switch
    - person
    - light

lovelace:
  mode: yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: https://hassnew.kaliwe.ru
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

zone:
- name: OpenWay
  latitude: 59.962516
  longitude: 30.334392
  icon: mdi:laptop

discovery:
  ignore:
  - yeelight

device_tracker:
- platform: snmp
  host: 192.168.88.1
  community: public
  baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1


notify:
- name: telegram
  platform: telegram
  chat_id: !secret telegram_bot_home_channel

telegram_bot:
- platform: polling
  api_key: !secret telegram_bot_key
  allowed_chat_ids:
    - !secret telegram_bot_home_channel

owntracks:
  mqtt_topic: "owntracks/#"

stream:
ffmpeg:
system_health:
map:
config:
mobile_app:


# --------------- Modules ---------------
yandex_smart_home: !include modules/alisa.yaml
scene: !include modules/scenes.yaml
person: !include modules/person.yaml
mqtt: !include modules/mqtt.yaml
sensor: !include modules/sensors.yaml
group: !include modules/groups.yaml
recorder: !include modules/recorder.yaml
logger: !include modules/logger.yaml

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts

# --------------- Devices ---------------
vacuum: !include devices/vacuums.yaml
fan: !include_dir_merge_list devices/fans
switch: !include devices/switches/switch.yaml
light: !include devices/lights/light.yaml
yeelight: !include devices/lights/yeelight.yaml
camera: !include devices/cameras.yaml
xiaomi_cooker: !include devices/rice_cooker.yaml
