title: My Awesome Home
views:
- title: Main
  panel: false
  # Makes the first card fill the view
  cards:
  #######################################################
  ######### Room camera config section
  #######################################################
  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "on"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_ffmpeg
      cavera_view: live
      entities:
      - vacuum.rockrobo
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch

  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "off"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_disabled
      cavera_view: live
      entities:
      - vacuum.rockrobo
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch

  #######################################################

  - type: custom:vertical-stack-in-card
    cards:
    - type: horizontal-stack
      cards:
      - type: sensor
        entity: sensor.temperature_room
        graph: line
      - type: sensor
        entity: sensor.humidity_room
        graph: line
      - type: sensor
        entity: sensor.co2
        graph: line

    - type: entities
      show_header_toggle: false
      entities:
      - light.bed_light
      - light.room_light
      - vacuum.rockrobo
      #- fan.xiaomi_miio_device

  - type: entities
    show_header_toggle: false
    type: entities
    title: Other lights
    entities:
    - light.kitchen_light
    - light.front_door_light
    - entity: switch.corridor_light_relay_switch_right
      name: Pentry
    - light.toilet_light
    - entity: switch.bathroom_light_relay_switch_right
      name: Bathroom

  - type: entities
    title: Wall switches
    show_header_toggle: false
    entities:
    - entity: switch.room_light_relay_switch_left
      name: Bed
    - entity: switch.room_light_relay_switch_right
      name: Room
    - entity: switch.kitchen_light_relay_switch
      name: Kitchen
    - entity: switch.corridor_light_relay_switch_left
      name: Front door switch
    - entity: switch.bathroom_light_relay_switch_left
      name: Toilet

  - type: entities
    title: Switches
    show_header_toggle: false
    entities:
    - entity: switch.sonoff_ac_1
      name: Bed garland
    - entity: switch.sonoff_ac_2
      name: Coach garland
    - entity: switch.sonoff_ac_3
      name: Christmas tree garland
    - entity: switch.room_camera_switch
      name: Camera room
    - entity: switch.kitchen_camera_switch
      name: Camera kitchen

- title: Vacuum
  panel: false
  cards:
  - type: entities
    title: Scripts
    show_header_toggle: false
    entities:
    - script.vacuum_go_to_clean
    - script.vacuum_tv_zone
    - script.vacuum_bed_zone
    - script.vacuum_kitchen_zone
    - script.vacuum_quoridor_zone
  - type: custom:vertical-stack-in-card
    cards:
    - type: entities
      show_header_toggle: false
      entities:
      - vacuum.rockrobo
    - type: 'custom:valetudo-map-card'
      entity: sensor.xiaomi_map
      rotate: 0
      #crop:
      #  top: 78
      #  bottom: 50
      #  left: 100
      #  right: 0
      vacuum_entity: vacuum.rockrobo
      map_scale: 2
      title:


- title: Scripts and scenes
  cards:
  - type: entities
    title: Scanner
    entities:
    - script.run_scan
  cards:
  - type: entities
    title: Common scripts
    entities:
    - script.human_arrive
    - script.human_leave
    - script.turn_off_lights

  - type: entities
    title: Scenes
    show_header_toggle: false
    entities:
    - scene.bright_bedroom
    - scene.dim_bedroom
    - scene.cinema
