title: My Awesome Home
views:
- title: Main
  panel: false
  # Makes the first card fill the view
  cards:
  #######################################################
  ######### Room camera config section
  #######################################################
  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "on"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_ffmpeg
      cavera_view: live
      entities:
      - vacuum.xiaomi_vacuum_cleaner
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch

  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "off"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_disabled
      cavera_view: live
      entities:
      - vacuum.xiaomi_vacuum_cleaner
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch

  #######################################################

  - type: horizontal-stack
    cards:
    - type: sensor
      entity: sensor.temperature_room
      graph: line
    - type: sensor
      entity: sensor.humidity_room
      graph: line
    - type: sensor
      entity: sensor.co2
      graph: line

  - type: entities
    show_header_toggle: false
    title: Room
    entities:
    - light.bed_light
    - light.room_light
    - vacuum.xiaomi_vacuum_cleaner
    - fan.xiaomi_miio_device

  - type: entities
    show_header_toggle: false
    type: entities
    title: Other lights
    entities:
    - light.kitchen_light
    - light.front_door_light
    - entity: switch.corridor_light_relay_switch_right
      name: Pentry
    - light.toilet_light
    - entity: switch.bathroom_light_relay_switch_right
      name: Bathroom

  - type: entities
    title: Wall switches
    show_header_toggle: false
    entities:
    - entity: switch.room_light_relay_switch_left
      name: Bed
    - entity: switch.room_light_relay_switch_right
      name: Room
    - entity: switch.kitchen_light_relay_switch
      name: Kitchen
    - entity: switch.corridor_light_relay_switch_left
      name: Front door switch
    - entity: switch.bathroom_light_relay_switch_left
      name: Toilet

  - type: entities
    title: Switches
    show_header_toggle: false
    entities:
    - entity: switch.sonoff_ac_1
      name: Bed garland
    - entity: switch.sonoff_ac_2
      name: Coach garland
    - entity: switch.sonoff_ac_3
      name: Christmas tree garland
    - entity: switch.room_camera_switch
      name: Camera room
    - entity: switch.kitchen_camera_switch
      name: Camera kitchen

- title: Scripts and scenes
  cards:
  - type: entities
    title: Common scripts
    entities:
    - script.human_arrive
    - script.human_leave
    - script.turn_off_lights

  - type: entities
    title: Scenes
    show_header_toggle: false
    entities:
    - scene.bright_bedroom
    - scene.dim_bedroom
    - scene.cinema
