title: My Awesome Home
views:
- title: Main
  panel: false
  # Makes the first card fill the view
  cards:
  #######################################################
  ######### Room camera config section
  #######################################################
  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "on"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_ffmpeg
      cavera_view: live
      entities:
      - vacuum.xiaomi_vacuum_cleaner
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch

  - type: conditional
    conditions:
    - entity: switch.room_camera_switch
      state: "off"
    card:
      type: picture-glance
      title: Room
      camera_image: camera.room_camera_disabled
      cavera_view: live
      entities:
      - vacuum.xiaomi_vacuum_cleaner
      - light.bed_light
      - light.room_light
      - switch.room_camera_switch
  #######################################################
  - type: glance
    entities:
    - entity: sensor.temperature_room
    - entity: sensor.humidity_room
    - entity: sensor.co2

  - type: entities
    show_header_toggle: false
    title: Room
    entities:
    - light.bed_light
    - light.room_light
    - vacuum.xiaomi_vacuum_cleaner
    - fan.xiaomi_miio_device

  - type: entity-filter
    card:
      show_header_toggle: false
      type: entities
      title: Other lights
    entities:
    - light.kitchen_light
    - light.yeelight_white_f0b4290f2bf4

    - light.gateway_light_7811dcb203d8
    - light.front_door_light
    state_filter:
    - "on"
    - "off"

  - type: entities
    title: Switches
    show_header_toggle: false
    entities:
    - entity: switch.wall_switch_left_158d000302ef25
      name: Toilet
    - entity: switch.wall_switch_right_158d000302ef25
      name: Bathroom
    - entity: switch.wall_switch_left_158d00014a5529
      name: Bed
    - entity: switch.wall_switch_right_158d00014a5529
      name: Room
    - entity: switch.wall_switch_158d00014a9c3c
      name: Kitchen
    - entity: switch.room_camera_switch
      name: Camera room

- title: Scripts and scenes
  cards:
  - type: entities
    title: Common scripts
    entities:
    - script.human_arrive
    - script.human_leave
    - script.turn_off_lights

  - type: entities
    title: Scenes
    show_header_toggle: false
    entities:
    - scene.bright_bedroom
    - scene.dim_bedroom
    - scene.cinema
