# vim: ts=2 sw=2:

- alias: Room left switch turn on if off on button click
  trigger:
    platform: state
    entity_id: sensor.room_light_relay_click
    to: 'left'
  condition:
    condition: state
    entity_id: switch.room_light_relay_switch_left
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.room_light_relay_switch_left

- alias: Room right switch turn on if off on button click
  trigger:
    platform: state
    entity_id: sensor.room_light_relay_click
    to: 'right'
  condition:
    condition: state
    entity_id: switch.room_light_relay_switch_right
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.room_light_relay_switch_right

- alias: Kitchen switch turn on if off on button click
  trigger:
    platform: state
    entity_id: sensor.kitchen_light_relay_click
    to: 'single'
  condition:
    condition: state
    entity_id: switch.kitchen_light_relay_switch
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_light_relay_switch

- alias: Front door switch turn on if off on button click
  trigger:
    platform: state
    entity_id: sensor.corridor_light_relay_click
    to: 'left'
  condition:
    condition: state
    entity_id: switch.corridor_light_relay_switch_left
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.corridor_light_relay_switch_left

- alias: Toilet switch turn on if off on button click
  trigger:
    platform: state
    entity_id: sensor.bathroom_light_relay_click
    to: 'left'
  condition:
    condition: state
    entity_id: switch.bathroom_light_relay_switch_left
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_light_relay_switch_left
