- platform: local_file
  name: room_camera_disabled
  file_path: room_camera_disabled.png
- platform: ffmpeg
  name: room_camera_ffmpeg
  input: -rtsp_transport tcp -i rtsp://192.168.30.7/ch0_1.h264
- platform: ffmpeg
  name: kitchen_camera_ffmpeg
  input: -rtsp_transport tcp -i rtsp://192.168.30.8/ch0_0.h264
