- platform: local_file
  name: room_camera_disabled
  file_path: room_camera_disabled.png

- platform: generic
  name: room_camera
  still_image_url: http://localhost:8765/picture/1/current
  # stream_source: http://192.168.20.3:8081

- platform: generic
  name: kitchen_camera
  still_image_url: http://localhost:8765/picture/2/current
  # stream_source: http://192.168.20.3:8082
