- alias: Kuzya automation light
  trigger:
    platform: mqtt
    topic: '/alisa/kuzya/light'
  action:
    service_template: 'light.turn_{{ "on" if trigger.payload_json.is_on else "off" }}'
    data_template:
      entity_id: '{{ trigger.payload_json.entity_id }}'

- alias: Kuzya automation all lights
  trigger:
    platform: mqtt
    topic: '/alisa/kuzya/all_lights'
  action:
    service_template: 'light.turn_{{ "on" if trigger.payload_json.is_on else "off" }}'
