- alias: "Update room light at key hour"
  trigger:
  - platform: time
    at: '01:01:00'
  - platform: time
    at: '06:01:00'
  - platform: time
    at: '22:01:00'
  action:
    service: script.turn_on
    entity_id: script.update_light_brightness_by_time
    data:
      variables:
        target: 'light.room_light'

- alias: "Update bed light at key hour"
  trigger:
  - platform: time
    at: '01:01:00'
  - platform: time
    at: '06:01:00'
  - platform: time
    at: '22:01:00'
  action:
    service: script.turn_on
    entity_id: script.update_light_brightness_by_time
    data:
      variables:
        target: 'light.bed_light'

- alias: "Update kitchen light at key hour"
  trigger:
  - platform: time
    at: '01:01:00'
  - platform: time
    at: '06:01:00'
  - platform: time
    at: '22:01:00'
  action:
    service: script.turn_on
    entity_id: script.update_light_brightness_by_time
    data:
      variables:
        target: 'light.kitchen_light'

- alias: "Update corridor light at key hour"
  trigger:
  - platform: time
    at: '01:01:00'
  - platform: time
    at: '06:01:00'
  - platform: time
    at: '22:01:00'
  action:
    service: script.turn_on
    entity_id: script.update_light_brightness_by_time
    data:
      variables:
        target: 'light.corridor_light'
