- alias: Automatically turn on lights in bedroom when someone come home
  trigger:
    platform: state
    entity_id: group.privileged_humans
    #from: not_home
    to: home
  action:
  - service: script.human_arrive

- alias: Turn off light when no one home
  trigger:
    platform: state
    entity_id: group.privileged_humans
    #from: home
    to: not_home
  action:
  - service: script.human_leave
