- alias: Corridor left button click
  trigger:
    platform: state
    entity_id: sensor.corridor_light_relay_click
    to: 'left'
  action:
    entity_id: light.front_door_light
    service: light.toggle

- alias: Room left button click
  trigger:
    platform: state
    entity_id: sensor.room_light_relay_click
    to: 'left'
  action:
    entity_id: light.bed_light
    service: light.toggle

- alias: Room right button click
  trigger:
    platform: state
    entity_id: sensor.room_light_relay_click
    to: 'right'
  action:
    entity_id: light.room_light
    service: light.toggle

- alias: Kitchen button click
  trigger:
    platform: state
    entity_id: sensor.kitchen_light_relay_click
    to: 'single'
  action:
    entity_id: light.kitchen_light
    service: light.toggle

